### ISSUE TITLE
运行BUG

### ISSUE THREAD

**Issue by mcoi-dev** [xy-cloud-cn/luogu-fortune#1]
```python
from PIL import Image, ImageDraw, ImageFont
```
执行了`pip3 install`，但是还是没有PIL头文件。

试了pillow也没用

**Comment by xy-cloud-cn** [comment]
运行环境是什么
可以尝试pip install pillow

**Comment by xy-cloud-cn** [comment]
提示安装成功了吗

**Comment by mcoi-dev** [comment]
安装成功了

**Comment by xy-cloud-cn** [comment]
能否提供一下运行错误信息和系统环境以及软件环境

**Comment by mcoi-dev** [comment]
成功了，建议直接写pip install Pillow，不要用txt了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: xy_cloud ***@***.***>
发送时间: Wednesday, December 7, 2022 6:27:54 PM
收件人: xy-cloud-cn/luogu-fortune ***@***.***>
抄送: minecraftoi ***@***.***>; Author ***@***.***>
主题: Re: [xy-cloud-cn/luogu-fortune] 运行BUG (Issue #1)


提示安装成功了吗

―

**Comment by Ninecloud2077** [comment]
可能是担心后期库太多
